/**
 * JQHTML v2 Instruction Processor
 * 
 * Processes instruction arrays generated by the parser
 * Uses v1's HTML string building approach for performance
 */

// Use global jQuery
declare const $: any;
import { Jqhtml_Component } from './component.js';
import { debug_attributes_enabled } from './config.js';
import { get_component_class, get_template } from './component-registry.js';

// Instruction types from parser
export interface TagInstruction {
  tag: [string, Record<string, any>, boolean]; // [name, attrs, selfClosing]
}

export interface RawTagInstruction {
  rawtag: [string, Record<string, any>, string]; // [name, attrs, rawContent]
}

export interface ComponentInstruction {
  comp: [string, Record<string, any>] | [string, Record<string, any>, ((context: any) => [any[], Jqhtml_Component]) | Record<string, (context: any) => [any[], Jqhtml_Component]>]; // [name, props, contentFn? | slots?]
}

export interface SlotInstruction {
  slot: [string, Record<string, any>, (context: any) => [any[], Jqhtml_Component]]; // [name, props, contentFn]
}

// ['_content', instructions, definer] - instructions written in another
// component's template (a slot body, or default content between a component's
// tags) and spliced in by content(). They render in `definer`, the component
// whose template contains the markup, so this in handler attributes, id=
// scoping and instantiator() agree with <%= %> and $sid, which are closures
// over the definer already. `definer` is absent only for legacy callers.
export type ContentInstruction = ['_content', Instruction[], Jqhtml_Component?];

export type Instruction = TagInstruction | RawTagInstruction | ComponentInstruction | SlotInstruction | ContentInstruction | string;

// Tracking data for second pass initialization
interface TagData {
  attrs: Record<string, any>;
  context: Jqhtml_Component;
}

interface ComponentData {
  name: string;
  props: Record<string, any>;
  contentFn?: (context: any) => [any[], Jqhtml_Component];
  slots?: Record<string, (context: any) => [any[], Jqhtml_Component]>;
  context: Jqhtml_Component;
}

// Base36 incrementing CID generator
// Format: aa, ab, ..., az, a0, ..., a9, ba, ..., zz, z9, aaa, ...
// First digit must always be a letter (a-z), subsequent digits can be a-z0-9
let _cid_increment = 'aa';

export function uid(): string {
  const current = _cid_increment;

  // Increment for next use
  const chars = _cid_increment.split('');
  let carry = true;

  // Process from right to left
  for (let i = chars.length - 1; i >= 0 && carry; i--) {
    const char = chars[i];

    if (char >= 'a' && char < 'z') {
      // a-y increments to next letter
      chars[i] = String.fromCharCode(char.charCodeAt(0) + 1);
      carry = false;
    } else if (char === 'z') {
      // z transitions to '0' (start of numeric range)
      chars[i] = '0';
      carry = false;
    } else if (char >= '0' && char < '9') {
      // 0-8 increments to next number
      chars[i] = String.fromCharCode(char.charCodeAt(0) + 1);
      carry = false;
    } else if (char === '9') {
      // 9 wraps back to 'a' with carry
      chars[i] = 'a';
      carry = true;
    }
  }

  // If we still have carry after processing all digits, we need more digits
  if (carry) {
    chars.unshift('a'); // Prepend new 'a' (first digit must be letter)
  }

  // Ensure first digit is never numeric
  if (chars[0] >= '0' && chars[0] <= '9') {
    chars[0] = 'a';
    chars.unshift('a');
  }

  _cid_increment = chars.join('');
  return current;
}

/**
 * Process an array of instructions and append to target
 * Uses v1 approach: build HTML string, set innerHTML, then initialize
 */
export function process_instructions(
  instructions: Instruction[],
  target: any,
  context: Jqhtml_Component,
  slots?: Record<string, SlotInstruction>
): void {
  // Build HTML string and track elements that need initialization
  const html: string[] = [];
  const tagElements: Record<string, TagData> = {};
  const components: Record<string, ComponentData> = {};

  // Process all instructions to build HTML
  for (const instruction of instructions) {
    process_instruction_to_html(instruction, html, tagElements, components, context, slots);
  }

  // Set innerHTML once - this is the performance win
  // Use native innerHTML for better performance
  target[0].innerHTML = html.join('');

  // Second pass: initialize special attributes and events.
  // One querySelectorAll over the freshly injected subtree, in document
  // order, rather than one querySelector per tracked element: a scan per
  // element made this pass quadratic in the size of the template. Child
  // components have not rendered yet (their elements are empty), so every
  // data-tid here belongs to this level.
  const root: Element = target[0];
  for (const el of Array.from(root.querySelectorAll('[data-tid]'))) {
    const tagData = tagElements[el.getAttribute('data-tid')!];
    el.removeAttribute('data-tid');
    if (tagData) {
      // Bind to the component whose template wrote this element, which for
      // spliced content is not the component being rendered.
      apply_attributes($(el), tagData.attrs, tagData.context);
    }
  }

  // Third pass: initialize and boot components in parallel
  // Like v1, all sibling components at this level boot simultaneously
  // DO NOT await - let children boot in background while parent continues
  for (const el of Array.from(root.querySelectorAll('[data-cid]'))) {
    const compData = components[el.getAttribute('data-cid')!];
    el.removeAttribute('data-cid');
    if (compData) {
      // Boot this component (which will render and boot its children recursively)
      // Fire and forget - don't wait for boot to complete
      initialize_component($(el), compData);
    }
  }
}

/**
 * Process a single instruction into HTML
 */
function process_instruction_to_html(
  instruction: Instruction,
  html: string[],
  tagElements: Record<string, TagData>,
  components: Record<string, ComponentData>,
  context: Jqhtml_Component,
  slots?: Record<string, SlotInstruction>
): void {
  if (typeof instruction === 'string') {
    // Raw HTML/text - no escaping, as requested
    html.push(instruction);
  } else if (Array.isArray(instruction)) {
    if (instruction[0] !== '_content' || !Array.isArray(instruction[1])) {
      return;
    }
    // Content written in another template renders in that template's component.
    const definer = instruction[2] || context;
    for (const item of instruction[1]) {
      process_instruction_to_html(item, html, tagElements, components, definer, slots);
    }
  } else if ('tag' in instruction) {
    // HTML tag
    process_tag_to_html(instruction, html, tagElements, components, context);
  } else if ('comp' in instruction) {
    // Component
    process_component_to_html(instruction, html, components, context);
  } else if ('slot' in instruction) {
    // Slot content
    process_slot_to_html(instruction, html, tagElements, components, context, slots);
  } else if ('rawtag' in instruction) {
    // Raw content tag (textarea, pre)
    process_rawtag_to_html(instruction, html);
  }
}

/**
 * Process a tag instruction to HTML
 */
function process_tag_to_html(
  instruction: TagInstruction,
  html: string[],
  tagElements: Record<string, TagData>,
  components: Record<string, ComponentData>,
  context: Jqhtml_Component
): void {
  const [tagName, attrs, selfClosing] = instruction.tag;
  
  // Check if we need to track this element for second pass
  const needsTracking = Object.keys(attrs).some(key =>
    key === '$sid' || key.startsWith('$') || key.startsWith('@') ||
    key.startsWith('on') ||
    key.startsWith('data-bind-') || key.startsWith('data-__-on-')
  );
  
  // Start building tag
  html.push(`<${tagName}`);
  
  // Add tracking ID if needed
  let tid: string | null = null;
  if (needsTracking) {
    tid = uid();
    html.push(` data-tid="${tid}"`);
    tagElements[tid] = { attrs, context };
  }
  
  // Add simple string/numeric attributes directly
  for (const [key, value] of Object.entries(attrs)) {
    if (key === 'data-sid' && !debug_attributes_enabled()) {
      continue;  // debug-only attribute; the scoped id is what $sid() resolves
    }
    if (!key.startsWith('$') && !key.startsWith('on') && !key.startsWith('@') &&
        !key.startsWith('data-bind-') && !key.startsWith('data-__-on-') &&
        (typeof value === 'string' || typeof value === 'number')) {
      // A hand-written `id` is emitted exactly as written - including on a tracked
      // element. It used to be rewritten to `<value>:<cid>` whenever the element
      // happened to carry some OTHER tracked attribute, so `<label id="x" @click=…>`
      // and `<label id="x">` disagreed. Per-instance ids are what $sid is for, and
      // the compiler emits those already scoped (codegen.ts), so they arrive here as
      // ordinary values and pass straight through.
      html.push(` ${key}="${escape_attribute(value)}"`);
    }
  }
  
  // Close opening tag
  if (selfClosing) {
    html.push(' />');
  } else {
    html.push('>');
  }
}

/**
 * A double quote inside an attribute value would end the attribute in the
 * HTML string this pass builds; an interpolated value can never legitimately
 * do that, so it is encoded. Nothing else is touched - the value is otherwise
 * emitted exactly as the template produced it.
 */
function escape_attribute(value: string | number): string {
  const s = typeof value === 'string' ? value : String(value);
  return s.indexOf('"') === -1 ? s : s.replace(/"/g, '&quot;');
}


/**
 * Process a component instruction to HTML
 */
function process_component_to_html(
  instruction: ComponentInstruction,
  html: string[],
  components: Record<string, ComponentData>,
  context: Jqhtml_Component
): void {
  const [componentName, originalProps, contentOrSlots] = instruction.comp;

  // Propagate lifecycle flags from parent to child if parent has them set
  // This allows a parent component with these flags to automatically
  // pass this behavior to all child components rendered in its template
  let props = originalProps;
  const parentArgs = (context as any).args;

  // Check if we need to propagate any flags.
  // Template-authored flags arrive with the '$' still on the key ($_load_only=false
  // compiles to props['$_load_only']) - honor both spellings so a child template can
  // opt out of a cascading parent flag with an explicit false.
  const own_use_cached_data = props.use_cached_data !== undefined ? props.use_cached_data : (props as any)['$use_cached_data'];
  const own_load_only = props._load_only !== undefined ? props._load_only : (props as any)['$_load_only'];
  const own_load_render_only = props._load_render_only !== undefined ? props._load_render_only : (props as any)['$_load_render_only'];

  const propagate_use_cached_data = parentArgs?.use_cached_data === true && own_use_cached_data === undefined;
  const propagate_load_only = parentArgs?._load_only === true && own_load_only === undefined;
  const propagate_load_render_only = parentArgs?._load_render_only === true && own_load_render_only === undefined;



  if (propagate_use_cached_data || propagate_load_only || propagate_load_render_only) {
    props = { ...originalProps };
    if (propagate_use_cached_data) {
      props.use_cached_data = true;
    }
    if (propagate_load_only) {
      props._load_only = true;
    }
    if (propagate_load_render_only) {
      props._load_render_only = true;
    }
  }

  // Determine if third parameter is a function (default content) or object (named slots)
  let contentFn: ((context: any) => [any[], Jqhtml_Component]) | undefined;
  let slots: Record<string, (context: any) => [any[], Jqhtml_Component]> | undefined;

  if (contentOrSlots) {
    if (typeof contentOrSlots === 'function') {
      // Single function = default content
      contentFn = contentOrSlots;
    } else if (typeof contentOrSlots === 'object') {
      // Object = named slots
      slots = contentOrSlots;
    }
  }

  // Generate unique ID for this component
  const cid = uid();

  // Get component class (or default) and template to determine tag name
  const ComponentClass = get_component_class(componentName) || Jqhtml_Component;
  const template = get_template(componentName);

  // Get tag name with precedence: _tag (invocation) > tag (template) > 'div'
  const tagName = props._tag || template.tag || 'div';

  // Create element with tracking ID
  html.push(`<${tagName} data-cid="${cid}"`);

  // Handle id attributes for components
  // The compiled code always generates both 'id' (scoped) and 'data-sid' (base) for $sid attributes
  // We just pass through what the compiler gave us - NEVER regenerate
  if (props['data-sid']) {
    const baseId = props['data-sid'];
    // The compiled code ALWAYS sets props['id'] with the correct scoped value
    // Just use it directly - it already has the correct parent _cid baked in
    // data-sid is debug-only: $sid() resolves via the scoped id, never this.
    html.push(
      debug_attributes_enabled()
        ? ` id="${props['id']}" data-sid="${baseId}"`
        : ` id="${props['id']}"`
    );
  }
  // Regular id passes through unchanged
  else if (props['id']) {
    html.push(` id="${props['id']}"`);
  }

  // Close tag - other attributes will be added during initialization
  html.push('></' + tagName + '>');

  // Track for initialization
  components[cid] = {
    name: componentName,
    props,
    contentFn,
    slots,
    context
  };
}

/**
 * Process a slot instruction to HTML
 */
function process_slot_to_html(
  instruction: SlotInstruction,
  html: string[],
  tagElements: Record<string, TagData>,
  components: Record<string, ComponentData>,
  context: Jqhtml_Component,
  parentSlots?: Record<string, SlotInstruction>
): void {
  const [slotName] = instruction.slot;
  
  // Check if parent provided content for this slot
  if (parentSlots && slotName in parentSlots) {
    const parentSlot = parentSlots[slotName];
    const [, slotProps, contentFn] = parentSlot.slot;
    
    // Execute slot content function with props
    const [content] = contentFn.call(context, slotProps);
    
    // Process the content to HTML
    for (const item of content) {
      process_instruction_to_html(item, html, tagElements, components, context);
    }
  } else if (slotName === 'default' && instruction.slot[2]) {
    // Use default slot content
    const [, , defaultFn] = instruction.slot;
    const [content] = defaultFn.call(context, {});
    for (const item of content) {
      process_instruction_to_html(item, html, tagElements, components, context);
    }
  }
}

/**
 * Process a rawtag instruction to HTML
 *
 * Raw content tags (textarea, pre) preserve exact whitespace without collapsing.
 * Content is inserted as textContent (not innerHTML) to prevent any interpretation.
 */
function process_rawtag_to_html(
  instruction: RawTagInstruction,
  html: string[]
): void {
  const [tagName, attrs, rawContent] = instruction.rawtag;

  // Build opening tag
  html.push(`<${tagName}`);

  // Add attributes
  for (const [key, value] of Object.entries(attrs)) {
    if (typeof value === 'string' || typeof value === 'number') {
      const escaped_value = String(value).replace(/"/g, '&quot;');
      html.push(` ${key}="${escaped_value}"`);
    } else if (typeof value === 'boolean' && value) {
      // Boolean attribute (e.g., disabled, readonly)
      html.push(` ${key}`);
    }
  }

  html.push('>');

  // Add raw content, preserving whitespace.
  //
  // <textarea> holds text and nothing else, so everything is escaped.
  //
  // <pre> holds phrasing content - <pre><code> is the standard code-block idiom - so
  // markup the author wrote is passed through. A '<' that does not begin a tag is
  // still escaped, which is what the HTML tokenizer itself does with a stray '<' and
  // keeps code samples such as "if (a < b)" rendering as written. Interpolated
  // values are escaped by the compiler before they reach this point.
  const is_raw_html_content = tagName.toLowerCase() === 'pre';

  const escaped_content = is_raw_html_content
    ? rawContent.replace(/<(?![a-zA-Z/!?])/g, '&lt;')
    : rawContent
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

  html.push(escaped_content);

  // Close tag
  html.push(`</${tagName}>`);
}

/**
 * Apply attributes with special handling to a DOM element
 *
 * This function processes various attribute types and applies them to the element:
 * - $sid: Creates component-scoped IDs (handled elsewhere in HTML generation)
 * - $*: Stored via jQuery .data() only (added to context.args for components)
 * - @*: Event handlers with automatic preventDefault and context binding
 * - on*: Standard event handlers with context binding
 * - data-*: Data attributes (stored both as attributes and via .data(), added to context.args)
 * - class: Merges with existing classes (no duplicates)
 * - style: Merges with existing styles (rule by rule, new values override)
 * - All other attributes: Applied directly to the element as standard HTML attributes
 *
 * For class and style attributes, merge logic is applied:
 * - class: Splits both existing and new, combines without duplicates
 * - style: Parses both into property maps, merges (new overrides), rebuilds
 *
 * Regular HTML attributes (href, title, role, etc.) are applied directly to the DOM
 * and are NOT converted to data attributes or added to component args.
 */
function apply_attributes(
  element: any,
  attrs: Record<string, any>,
  context: Jqhtml_Component
): void {
  for (const [key, value] of Object.entries(attrs)) {
    if (key === '$sid' || key === 'id') {
      // Already handled in HTML generation
      continue;
    } else if (key.startsWith('$')) {
      // $ attributes: store via jQuery .data() only
      // Does NOT create data-* attributes on the DOM element
      const dataKey = key.substring(1);
      element.data(dataKey, value);
    // } else if (key.startsWith('@')) {
    //   // Event handler with @ prefix (e.g., @click)
    //   const eventName = key.substring(1);  // Remove @ to get 'click'
    //   if (typeof value === 'function') {
    //     element.on(eventName, function(e: any) {
    //       e.preventDefault();  // Auto-preventDefault as per JQHTML design
    //       // Bind 'this' to the component context and call the function
    //       value.bind(context)(e, element);
    //     });
    //   } else {
    //     console.warn("(JQHTML) Tried to assign a non function to @ event handler "+key)
    //   }
    } else if (key.startsWith('data-__-on-')) {
      // Event handler
      const eventName = key.substring(11); // 'data-__-on-'.length = 11
      if (typeof value === 'function') {
        element.on(eventName, function(e: any) {
          value.bind(context)(e, element);
        });
      } else {
        console.warn("(JQHTML) Tried to assign a non function to on event handler "+key)
      }
    } else if (key.startsWith('on')) {
      // Event handler
      const eventName = key.substring(2);
      if (typeof value === 'function') {
        element.on(eventName, function(e: any) {
          value.bind(context)(e, element);
        });
      } else {
        console.warn("(JQHTML) Tried to assign a non function to on event handler "+key)
      }
    } else if (key.startsWith('data-')) {
      // data-sid is debug-only - suppressed entirely in production
      if (key === 'data-sid' && !debug_attributes_enabled()) {
        continue;
      }
      // Data attributes - go into DOM
      const attrValue = typeof value === "string" ? value.trim() : value;
      element.attr(key, attrValue);
      // Get version without 'data-' prefix
      const dataKey = key.substring(5);
      // Always set element.data
      element.data(dataKey, value);
    } else if (key === 'class') {
      // Handle class attribute with merge logic
      const existingClasses = element.attr('class');

      // Debug logging
      if ((window as any).jqhtml?.debug?.enabled) {
        console.log(`[InstructionProcessor] Merging class attribute:`, {
          existing: existingClasses,
          new: value
        });
      }

      if (!existingClasses) {
        // No existing classes - set directly
        const attrValue = typeof value === "string" ? value.trim() : value;
        element.attr('class', attrValue);
      } else {
        // Merge classes - split and add if not present
        const existing = existingClasses.split(/\s+/).filter(c => c);
        const newClasses = String(value).split(/\s+/).filter(c => c);
        for (const newClass of newClasses) {
          if (!existing.includes(newClass)) {
            existing.push(newClass);
          }
        }
        element.attr('class', existing.join(' '));
      }

      // Debug logging result
      if ((window as any).jqhtml?.debug?.enabled) {
        console.log(`[InstructionProcessor] Class after merge:`, element.attr('class'));
      }
    } else if (key === 'style') {
      // Handle style attribute with merge logic
      const existingStyle = element.attr('style');
      if (!existingStyle) {
        // No existing style - set directly
        const attrValue = typeof value === "string" ? value.trim() : value;
        element.attr('style', attrValue);
      } else {
        // Merge styles rule by rule
        // Parse existing styles into map
        const styleMap: Record<string, string> = {};
        existingStyle.split(';').forEach(rule => {
          const [prop, val] = rule.split(':').map(s => s.trim());
          if (prop && val) {
            styleMap[prop] = val;
          }
        });

        // Parse and merge new styles
        String(value).split(';').forEach(rule => {
          const [prop, val] = rule.split(':').map(s => s.trim());
          if (prop && val) {
            styleMap[prop] = val;  // Override existing or add new
          }
        });

        // Rebuild style string
        const mergedStyle = Object.entries(styleMap)
          .map(([prop, val]) => `${prop}: ${val}`)
          .join('; ');
        element.attr('style', mergedStyle);
      }
    } else {
      // Regular HTML attributes - apply directly to the element
      // These do NOT become data attributes or go into context.args
      // Examples: href, title, role, aria-*, tabindex, etc.
      if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
        const attrValue = typeof value === "string" ? value.trim() : String(value);
        element.attr(key, attrValue);
      } else if (typeof value === 'object') {
        // Complex values can't be DOM attributes, store as jQuery data only
        console.warn(`(JQHTML) Unexpected value for '${key}' on`, element);
        // element.data(key, value);
      }
    }
  }
}

/**
 * Initialize a component on a DOM element
 *
 * This function sets up a component instance on the given element by:
 * 1. Building the component's CSS classes (component name + Jqhtml_Component)
 * 2. Applying attributes from Define tag (template.defaultAttributes) first
 * 3. Applying attributes from invocation (props) second, which override Define attributes
 * 4. Creating the component instance
 *
 * Attribute handling rules:
 * - 'as': Determines tag name (handled in process_component_to_html)
 * - 'class': Merged from both Define and invocation
 * - 'style': Merged with rule-by-rule precedence (invocation wins conflicts)
 * - '$*' and 'data-*': Become data attributes and component args
 * - '@*': Event handlers (only allowed in invocation, not Define)
 * - All other attributes: Applied directly to DOM element
 */
async function initialize_component(
  element: any,
  compData: ComponentData
): Promise<void> {
  const { name, props, contentFn, slots, context } = compData;

  // Get component class (use default Jqhtml_Component if not registered)
  const ComponentClass = get_component_class(name) || Jqhtml_Component;

  // Apply invocation attributes to the element
  // The component constructor will handle defaultAttributes
  // Filter out internal props that start with underscore
  const invocationAttrs: Record<string, any> = {};
  for (const [key, value] of Object.entries(props)) {
    if (!key.startsWith('_')) {
      invocationAttrs[key] = value;
    }
  }

  // Debug logging
  if ((window as any).jqhtml?.debug?.enabled) {
    console.log(`[InstructionProcessor] Applying invocation attributes for ${name}:`, invocationAttrs);
  }

  // Apply invocation attributes (component constructor will apply defaultAttributes first)
  apply_attributes(element, invocationAttrs, context);

  // Component will set its own data-cid during construction
  // No need to add any tracking attributes here

  // Prepare options for component constructor
  // Only pass the content function - all other attributes are already on the DOM
  const options: any = {};

  if (contentFn) {
    options._innerhtml_function = contentFn;
  }

  // Pass named slots if provided
  if (slots) {
    options._slots = slots;
  }

  // Always pass the invocation name: it is what component_name() reports, it
  // selects the template when the class is inherited via an extends chain or
  // is the bare Jqhtml_Component, and it is the class the element carries.
  options._component_name = name;

  // Pass lifecycle truncation flags via options (not DOM attributes, since _ prefix is filtered).
  // Accept both the plain key (cascaded/programmatic) and the '$'-prefixed key (template-authored).
  if (props._load_only === true || (props as any)['$_load_only'] === true) {
    options._load_only = true;
  }
  if (props._load_render_only === true || (props as any)['$_load_render_only'] === true) {
    options._load_render_only = true;
  }

  // Create component instance - element first, then options
  const instance = new ComponentClass(element, options);

  // Set the instantiator (the component that rendered this one in their template)
  (instance as any)._instantiator = context;

  // Boot the component immediately - this runs its full lifecycle
  await (instance as any)._boot();
}

/**
 * Utility to extract slots from instructions
 */
export function extract_slots(instructions: Instruction[]): Record<string, SlotInstruction> {
  const slots: Record<string, SlotInstruction> = {};
  
  for (const instruction of instructions) {
    if (typeof instruction === 'object' && 'slot' in instruction) {
      const [name] = instruction.slot;
      slots[name] = instruction;
    }
  }
  
  return slots;
}